name: CI_build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: setup-minikube
      uses: medyagh/setup-minikube@v0.0.11
      with:
          cpus: 2
          memory: 6144
    - name: check pods
      run: kubectl get pods -A
    - name: set docker environment for k8s
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker-compose -f docker-compose-ci.yaml build --no-cache
    - name: check docker images
      run: minikube image ls --format table

    - uses: hashicorp/setup-terraform@v2   
    - name: terraform-init
      run: terraform -chdir=terraform-k8s init
    - name: terraform-plan
      run: terraform -chdir=terraform-k8s plan
      
# the current version of CI stops at this point, as I couldn't run all services with terraform apply, I suspect that occurs due to resources limitations
# on Github Actions free tier.
# Optional TODO: Try to fix it and develop further. Maybe try macOS machine instead of Ubuntu which offers more resources, although is less performant.
#
#     - name: terraform-apply
#       run: terraform -chdir=terraform-k8s apply -auto-approve 

#     - name: Sleep for 30 seconds
#       run: sleep 30s
#       shell: bash
#     - name: check pods
#       run: kubectl get pods -A
